### PR TITLE
sheng time_format fixes + queue update question fix

### LINKED ISSUE #306: change metrics time helped from decimal to time
eg avg time helped = 7.90 minutes => avg time helped 7:54

### PR DESCRIPTION
**Pull request by Skyism**
2 fixes:

1. Added catch statement so if the student refuses to change their question and enter the same one as before it doesn't crash the client.
2. Implement what sheng wants with the time being mm:ss instead of minutes in decimal

EDIT: fixed syntax / del console log

### CODE REVIEW

File: server/controllers/metrics.js [hunk 1]
```diff
@@ -109,6 +109,11 @@ exports.get_avg_time_per_question = (req, res) => {
 
         if (count != 0) averageTime /= count;
 
+        const minutes = Math.floor(averageTime);
+        console.log(minutes);
```
Comment (azhang45) [inline server/controllers/metrics.js]: me when debugging logs </3

File: client/src/components/metrics/PersonalStats.tsx [hunk 2]
```diff
@@ -87,7 +87,7 @@ export default function PersonalStats() {
           </Grid>
           <Grid sx={{textAlign: 'center'}}>
             <Typography variant='h6' fontWeight='bold'>Avg. Time Spent Per Question (min)</Typography>
-            <Typography variant='h3' sx={{mt: 2}} fontWeight='bold'>{Number(averageHelpTime).toFixed(2)}</Typography>
+            <Typography variant='h3' sx={{mt: 2}} fontWeight='bold'>{(averageHelpTime)}</Typography>
```
Comment (azhang45) [inline client/src/components/metrics/PersonalStats.tsx]: very minor but is the parentheses in the curly braces intentional am i tripping

Comment (Skyism) [reply client/src/components/metrics/PersonalStats.tsx]: you are correct 🥀

**Review by jacksontromero — APPROVED** [review]
lgtm!
